### ISSUE TITLE
support mandatory config on iOS

### ISSUE THREAD

**Issue by jasmineic** [InvisibleCommerce/shipped-suite-ios-client-sdk#19]
Widget design
https://www.figma.com/file/ryeFqjwQeMqdFzL8a8hrFz/Shipped-%E2%80%A2-Design-System-(VD)?node-id=34650%3A40779&t=RpenQ4xWbv1Br44h-4

Property for config should be aligned with JS client, isMandatory, boolean.

**Comment by stevenou** [comment]
@jasmineic because the iOS SDK works a little differently (it gets loaded once, not on every page), that means a simple boolean value would not be able to handle the tomo use case. it would need to be implemented with a threshold.

**Comment by stevenou** [comment]
@jasmineic let's have a meeting with @catalin-invisible and @hoyelo to discuss approach and timeline?

**Comment by jasmineic** [comment]
Sounds good. Let's discuss today during the sync.

**Comment by jasmineic** [comment]
Per discussion, isMandatory config will be able to support the following
- Boolean
- Number (min threshold)
- Range
