### ISSUE TITLE
support isInformational

### ISSUE THREAD

**Issue by jasmineic** [InvisibleCommerce/shipped-suite-ios-client-sdk#22]
Display informational widget and modal when it's merchant paid. 

[Widget reference](https://www.figma.com/file/ryeFqjwQeMqdFzL8a8hrFz/Shipped-%E2%80%A2-Design-System-(VD)?node-id=34650%3A40766&t=5y3k2ukf5HMT6CUG-4)

[Modal reference](https://www.figma.com/file/ryeFqjwQeMqdFzL8a8hrFz/Shipped-%E2%80%A2-Design-System-(VD)?node-id=34618%3A39649&t=5y3k2ukf5HMT6CUG-4)

Property (default value)
`isInformational: false,`

**Comment by hoyelo** [comment]
@jasmineic Is it `false` by default? That means the fee label will be hidden as default?

**Comment by jasmineic** [comment]
Yes, false is the default value. 

False mean that the widget is not informational and the fee is shown.
