### ISSUE TITLE
support multi-currency

### ISSUE THREAD

**Issue by jasmineic** [InvisibleCommerce/shipped-suite-ios-client-sdk#23]
Ability to support multi-currency

Property
`currency: 'USD',`

Specify the currency the Shipped offer will be displayed in

**Comment by hoyelo** [comment]
@stevenou Do the formatted values `shield_fee_with_currency` and `green_fee_with_currency` need to be called back?

**Comment by stevenou** [comment]
off the top of my head, I feel like the callback should include both base currency values as well as "with currency" values. I imagine we already established a pattern for how to do this in the JS SDK, but I cannot remember... @catalin-invisible can you please pitch in?

**Comment by catalin-invisible** [comment]
I'm not sure I understand the question, to be called back where exactly?

**Comment by hoyelo** [comment]
@catalin-invisible Some data will be called back from mobile sdk to the merchant's app, I'm not sure the web.

**Comment by catalin-invisible** [comment]
oh, in the `onChange` callback where we provide `isSelected` and `totalFee` values?

**Comment by hoyelo** [comment]
yes.

**Comment by catalin-invisible** [comment]
I think it could help, the merchant could use the already formatted value we're providing as opposed to format it themselves.

@stevenou As a note, currently, those formatted values that come from offers request are not used anywhere in JS SDK. At the time I implemented multi-currency we did not had those values coming from the backend so I had implemented then a formatting function in frontend (based on a separate request to get currency formatting details).

**Comment by catalin-invisible** [comment]
so now, on JS SDK, we only provide `isSelected` and `totalFee` in the callback, (`totalFee` as an absolute value, with no currency information)

**Comment by catalin-invisible** [comment]
one issue to consider though: we're providing a total in the callback, but the formatted prices come separate: a string for sheild and a string for green - we don't have a combined formatted price

**Comment by hoyelo** [comment]
Yes, could we add `green_shield_fee_with_currency` in the offers as the combined price? @stevenou

**Comment by stevenou** [comment]
unfortunately it doesn't really make sense to do that the way it's currently architected. let's just stick with only callback for `totalFee` without currency, for now. so far, there isn't actually any use case that even uses `totalFee` from the callback, let alone fee with currency.

**Comment by hoyelo** [comment]
For the mobile SDKs, only `isSelected`, `shieldFee` and `greenFee` are provided, but there is no `totalFee`, do I need to use `totalFee` instead of `shieldFee` and `greenFee`?

**Comment by stevenou** [comment]
let's do whatever it is that the JS SDK does. so I believe that is `isSelected` and `totalFee`, right? @catalin-invisible

**Comment by catalin-invisible** [comment]
yes

**Comment by hoyelo** [comment]
okay thanks!
